//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularjsSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Email
    {
        public Email()
        {
            this.Users = new HashSet<User>();
        }
    
        public int EMailID { get; set; }
        public int PersonID { get; set; }
        public int EMailTypeID { get; set; }
        public Nullable<int> EmailSMSProviderID { get; set; }
        public string EMailAddress { get; set; }
        public Nullable<bool> IsPrimary { get; set; }
    
        public virtual ICollection<User> Users { get; set; }
    }
}
