//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularjsSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int UserID { get; set; }
        public int UserLevelID { get; set; }
        public Nullable<int> DistrictID { get; set; }
        public int PersonID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public Nullable<bool> Superuser { get; set; }
        public Nullable<bool> Active { get; set; }
        public System.DateTime c_date { get; set; }
        public string SID { get; set; }
        public Nullable<int> Account_EMailID { get; set; }
        public bool Locked { get; set; }
        public int RetryCount { get; set; }
        public int ForgotCount { get; set; }
    
        public virtual Email Email { get; set; }
    }
}
